apiVersion: apps/v1
kind: Deployment
metadata:
  name: pishop-frontend
  labels:
    app: pishop-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pishop-frontend
  template:
    metadata:
      labels:
        app: pishop-frontend
    spec:
      containers:
        - name: pishop-frontend
          image: ghcr.io/pilab-dev/pishop:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          env:
            - name: NEXT_PUBLIC_PISHOP_API_URL
              value: "https://shop.vm3.pilab.hu"
      imagePullSecrets:
        - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pishop-api
  labels:
    app: pishop-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pishop-api
  template:
    metadata:
      labels:
        app: pishop-api
    spec:
      containers:
        - name: pishop-api
          image: ghcr.io/pilab-dev/pishop-api:latest
          ports:
            - containerPort: 8083
          env:
            - name: PORT
              value: "8083"
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: pishop-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pishop-frontend-service
spec:
  selector:
    app: pishop-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: pishop-api-service
spec:
  selector:
    app: pishop-api
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pishop-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pishop-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/redirect-to-https: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - shop.vm3.pilab.hu
      secretName: pishop-tls
  rules:
    - host: shop.vm3.pilab.hu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pishop-frontend-service
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: pishop-api-service
                port:
                  number: 8083
