/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {
    bentoBox: BentoBoxProps;
    bestSellers: BestSellersProps;
    featuredProducts: FeaturedProductsProps;
    hero: HeroBlockProps;
    hotDealsBlock: HotDealsBlock;
    productGrid: ProductGridProps;
    productShowcase: ProductShowcaseProps;
    promotionalBanner: PromotionalBannerProps;
  };
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    users: User;
    promotionalContent: PromotionalContent;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    promotionalContent: PromotionalContentSelect<false> | PromotionalContentSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    header: Header;
    footer: Footer;
    promotions: Promotion;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    promotions: PromotionsSelect<false> | PromotionsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BentoBoxProps".
 */
export interface BentoBoxProps {
  /**
   * Optional title for this bento box section
   */
  title?: string | null;
  /**
   * Add items to display in the bento box grid
   */
  items?:
    | {
        /**
         * Content to display in this bento box item
         */
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        /**
         * How many columns this item should span
         */
        colSpan?: ('1' | '2' | '3') | null;
        /**
         * How many rows this item should span
         */
        rowSpan?: ('1' | '2' | '3') | null;
        /**
         * Background color for this bento box item
         */
        backgroundColor?: ('default' | 'primary' | 'secondary' | 'accent' | 'white') | null;
        /**
         * Text alignment within this item
         */
        textAlign?: ('left' | 'center' | 'right') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Layout settings for the bento box
   */
  layout?: {
    /**
     * Number of columns in the grid
     */
    columns?: ('2' | '3' | '4') | null;
    /**
     * Gap between grid items
     */
    gap?: ('2' | '4' | '6') | null;
    /**
     * Maximum width of the bento box container
     */
    maxWidth?: ('768' | '1024' | '1280' | 'full') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'bentoBox';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BestSellersProps".
 */
export interface BestSellersProps {
  /**
   * Title for the best sellers section
   */
  title?: string | null;
  /**
   * Optional subtitle for this section
   */
  subtitle?: string | null;
  /**
   * How to source the best-selling products
   */
  source: 'promotionalContent' | 'manual' | 'auto';
  /**
   * Select promotional content with best sellers
   */
  promotionalContent?: (string | null) | PromotionalContent;
  /**
   * Manually selected best-selling products
   */
  products?:
    | {
        /**
         * Select product from storefront
         */
        productId: string;
        /**
         * Sales rank/position (for display purposes)
         */
        salesRank?: number | null;
        /**
         * Badge text to display (automatically generated based on rank)
         */
        badge?: string | null;
        /**
         * Sort order within this block
         */
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Settings for automatic best seller selection
   */
  autoSettings?: {
    /**
     * Timeframe to consider for best sellers
     */
    timeframe?: ('7days' | '30days' | '90days' | 'all') | null;
    /**
     * Limit to specific category from storefront API (optional)
     */
    category?: string | null;
    /**
     * Minimum sales threshold
     */
    minSales?: number | null;
  };
  /**
   * Display settings for the best sellers section
   */
  displaySettings?: {
    /**
     * How to display the best sellers
     */
    layout?: ('grid' | 'carousel' | 'rankedList' | 'hero') | null;
    /**
     * Number of columns (for grid layout)
     */
    columns?: ('2' | '3' | '4' | '6') | null;
    /**
     * Show sales rankings/numbers
     */
    showRankings?: boolean | null;
    /**
     * Show 'Best Seller' badges
     */
    showBadges?: boolean | null;
    /**
     * Maximum number of products to display
     */
    maxItems?: number | null;
  };
  /**
   * Call-to-action settings
   */
  callToAction?: {
    /**
     * Button text
     */
    text?: string | null;
    /**
     * URL or path to link to (e.g., best-sellers collection)
     */
    link?: string | null;
    style?: ('primary' | 'secondary' | 'outline' | 'link') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'bestSellers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotionalContent".
 */
export interface PromotionalContent {
  id: string;
  /**
   * Display title for this promotional content
   */
  title: string;
  /**
   * Type of promotional content
   */
  type: 'featuredProducts' | 'bestSellers' | 'campaign' | 'seasonal' | 'flashSale';
  /**
   * Description of this promotional content
   */
  description?: string | null;
  /**
   * Whether this promotional content is currently active
   */
  isActive?: boolean | null;
  /**
   * Priority order (higher numbers appear first)
   */
  priority?: number | null;
  /**
   * When this promotion should start (optional)
   */
  startDate?: string | null;
  /**
   * When this promotion should end (optional)
   */
  endDate?: string | null;
  /**
   * Products to feature in this promotional content
   */
  products?:
    | {
        /**
         * Product ID or slug from the webshop engine
         */
        productId: string;
        /**
         * Optional custom title to display instead of product name
         */
        overrideTitle?: string | null;
        /**
         * Optional custom description to display
         */
        overrideDescription?: string | null;
        /**
         * Badge text to display (e.g., "NEW", "SALE", "BEST SELLER")
         */
        badge?: string | null;
        /**
         * Sort order within this promotional content
         */
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Hero image for this promotional content
   */
  heroImage?: (string | null) | Media;
  /**
   * Call-to-action settings
   */
  callToAction?: {
    /**
     * Button text
     */
    text?: string | null;
    /**
     * URL or path to link to
     */
    link?: string | null;
    style?: ('primary' | 'secondary' | 'outline') | null;
  };
  /**
   * SEO and display metadata
   */
  metadata?: {
    /**
     * SEO title override
     */
    seoTitle?: string | null;
    /**
     * SEO description override
     */
    seoDescription?: string | null;
    /**
     * How to display this promotional content
     */
    displayStyle?: ('grid' | 'carousel' | 'list' | 'hero') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedProductsProps".
 */
export interface FeaturedProductsProps {
  /**
   * Optional title for this featured products section
   */
  title?: string | null;
  /**
   * Optional subtitle for this section
   */
  subtitle?: string | null;
  /**
   * How to source the featured products
   */
  source: 'manual' | 'promotionalContent' | 'collection';
  /**
   * Select promotional content to display
   */
  promotionalContent?: (string | null) | PromotionalContent;
  /**
   * Select collection from storefront API to feature products from
   */
  collection?: string | null;
  /**
   * Manually selected products to feature
   */
  products?:
    | {
        /**
         * Select product from storefront
         */
        productId: string;
        /**
         * Optional custom title to display instead of product name
         */
        overrideTitle?: string | null;
        /**
         * Optional custom description to display
         */
        overrideDescription?: string | null;
        /**
         * Badge text to display (e.g., 'NEW', 'SALE', 'FEATURED')
         */
        badge?: string | null;
        /**
         * Sort order within this block
         */
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Display settings for this featured products section
   */
  displaySettings?: {
    /**
     * How to display the featured products
     */
    layout?: ('grid' | 'carousel' | 'list' | 'hero') | null;
    /**
     * Number of columns (for grid layout)
     */
    columns?: ('1' | '2' | '3' | '4' | '6') | null;
    /**
     * Show product prices
     */
    showPrice?: boolean | null;
    /**
     * Show product badges
     */
    showBadges?: boolean | null;
    /**
     * Maximum number of products to display
     */
    maxItems?: number | null;
  };
  /**
   * Call-to-action settings for this section
   */
  callToAction?: {
    /**
     * Button text (e.g., 'Shop Now', 'View All')
     */
    text?: string | null;
    /**
     * URL or path to link to
     */
    link?: string | null;
    style?: ('primary' | 'secondary' | 'outline' | 'link') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredProducts';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlockProps".
 */
export interface HeroBlockProps {
  /**
   * Select a product to display in the hero section
   */
  product: {
    /**
     * Select product from storefront to feature in hero section
     */
    productSlug: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HotDealsBlock".
 */
export interface HotDealsBlock {
  products: {
    product?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'hotDealsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductGridProps".
 */
export interface ProductGridProps {
  /**
   * Optional title for this product grid section
   */
  title?: string | null;
  /**
   * Optional subtitle for this section
   */
  subtitle?: string | null;
  /**
   * How to source the products for this grid
   */
  source: 'manual' | 'collection' | 'latest' | 'featured';
  /**
   * Select collection from storefront API to display products from
   */
  collection?: string | null;
  /**
   * Manually selected products to display in the grid
   */
  products?:
    | {
        /**
         * Select product from storefront
         */
        productId: string;
        /**
         * Sort order within this block
         */
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Display settings for this product grid
   */
  displaySettings?: {
    /**
     * Display products in grid or list format
     */
    view?: ('grid' | 'list') | null;
    /**
     * Number of columns (for grid view only)
     */
    columns?: ('2' | '3' | '4' | '5' | '6') | null;
    /**
     * Maximum number of products to display
     */
    maxItems?: number | null;
    /**
     * Show product prices
     */
    showPrices?: boolean | null;
    /**
     * Show product action buttons (add to cart, etc.)
     */
    showButtons?: boolean | null;
  };
  /**
   * Call-to-action settings for this section
   */
  callToAction?: {
    /**
     * Button text (e.g., 'View All Products', 'Shop Now')
     */
    text?: string | null;
    /**
     * URL or path to link to
     */
    link?: string | null;
    style?: ('primary' | 'secondary' | 'outline' | 'link') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'productGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductShowcaseProps".
 */
export interface ProductShowcaseProps {
  /**
   * Optional title for this showcase section
   */
  title?: string | null;
  /**
   * Optional subtitle
   */
  subtitle?: string | null;
  /**
   * Type of content to showcase
   */
  showcaseType: 'products' | 'category' | 'collection' | 'brand' | 'seasonal';
  /**
   * How to source the showcase content
   */
  source: 'manual' | 'promotionalContent' | 'dynamic';
  /**
   * Select category to showcase (from storefront API)
   */
  category?: string | null;
  /**
   * Select collection to showcase (from storefront API)
   */
  collection?: string | null;
  /**
   * Select promotional content to display
   */
  promotionalContent?: (string | null) | PromotionalContent;
  /**
   * Products to showcase
   */
  products?:
    | {
        /**
         * Select product from storefront
         */
        productId: string;
        /**
         * Highlight this product (larger, different styling)
         */
        highlight?: boolean | null;
        /**
         * Custom display title
         */
        customTitle?: string | null;
        /**
         * Badge text (e.g., 'NEW', 'POPULAR')
         */
        badge?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Settings for dynamic content
   */
  dynamicSettings?: {
    sortBy?: ('newest' | 'priceAsc' | 'priceDesc' | 'popular' | 'bestSelling' | 'random') | null;
    filterBy?: {
      /**
       * Filter by category (from storefront API)
       */
      category?: string | null;
      priceRange?: {
        /**
         * Minimum price
         */
        min?: number | null;
        /**
         * Maximum price
         */
        max?: number | null;
      };
      /**
       * Filter by tags (comma-separated)
       */
      tags?: string | null;
    };
  };
  /**
   * Layout and display settings
   */
  layout?: {
    style?: ('grid' | 'carousel' | 'masonry' | 'list' | 'heroGrid') | null;
    columns?: ('2' | '3' | '4' | '5' | '6') | null;
    aspectRatio?: ('square' | 'portrait' | 'landscape' | 'wide') | null;
    spacing?: ('tight' | 'normal' | 'loose') | null;
  };
  /**
   * What content to show on products
   */
  contentSettings?: {
    showTitle?: boolean | null;
    showPrice?: boolean | null;
    showComparePrice?: boolean | null;
    showBadges?: boolean | null;
    /**
     * Show quick add to cart button
     */
    showQuickAdd?: boolean | null;
    hoverEffect?: ('zoom' | 'lift' | 'overlay' | 'none') | null;
  };
  /**
   * Section call-to-action
   */
  callToAction?: {
    /**
     * Button text
     */
    text?: string | null;
    /**
     * URL or path
     */
    link?: string | null;
    position?: ('end' | 'topRight' | 'bottomCenter') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'productShowcase';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PromotionalBannerProps".
 */
export interface PromotionalBannerProps {
  /**
   * Banner content (text, links, etc.)
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Background image for the banner (optional)
   */
  backgroundImage?: (string | null) | Media;
  /**
   * Background color (hex code) - used if no background image
   */
  backgroundColor?: string | null;
  /**
   * Text color (hex code)
   */
  textColor?: string | null;
  /**
   * Banner height
   */
  height?: ('small' | 'medium' | 'large' | 'full') | null;
  /**
   * Content alignment
   */
  alignment?: ('left' | 'center' | 'right') | null;
  /**
   * Call-to-action button settings
   */
  callToAction?: {
    /**
     * Button text
     */
    text?: string | null;
    /**
     * URL or path to link to
     */
    link?: string | null;
    style?: ('primary' | 'secondary' | 'outline' | 'ghost') | null;
    position?: ('inline' | 'below') | null;
  };
  /**
   * Banner behavior settings
   */
  behavior?: {
    /**
     * Allow users to dismiss the banner
     */
    dismissible?: boolean | null;
    /**
     * Make banner sticky/fixed position
     */
    sticky?: boolean | null;
    /**
     * Entrance animation
     */
    animation?: ('none' | 'fadeIn' | 'slideDown' | 'pulse') | null;
  };
  /**
   * When to show this banner
   */
  scheduling?: {
    /**
     * Start showing banner from this date
     */
    startDate?: string | null;
    /**
     * Stop showing banner after this date
     */
    endDate?: string | null;
    /**
     * Target specific audience
     */
    targetAudience?: ('all' | 'new' | 'returning' | 'authenticated') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'promotionalBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  tags?:
    | {
        /**
         * Add and manage tags for this document.
         */
        tags?:
          | {
              tag: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  elements: (
    | BentoBoxProps
    | FeaturedProductsProps
    | HeroBlockProps
    | HotDealsBlock
    | ProductGridProps
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | FormBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact' | 'centeredImpact' | 'sideBySide' | 'techHero';
    style?: ('standard' | 'card') | null;
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (string | null) | Media;
  };
  markdown?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  heroImage?: (string | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (string | Post)[] | null;
  /**
   * Categories from storefront API (comma-separated slugs)
   */
  categories?: string | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (string | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  role: 'admin' | 'customer';
  points?: number | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  /**
   * Categories from storefront API (comma-separated slugs)
   */
  categories?: string | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: string | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: string | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: string | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'promotionalContent';
        value: string | PromotionalContent;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: string | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  tags?:
    | T
    | {
        tags?:
          | T
          | {
              tag?: T;
              id?: T;
            };
        id?: T;
      };
  elements?:
    | T
    | {
        bentoBox?: T | BentoBoxPropsSelect<T>;
        featuredProducts?: T | FeaturedProductsPropsSelect<T>;
        hero?: T | HeroBlockPropsSelect<T>;
        hotDealsBlock?: T | HotDealsBlockSelect<T>;
        productGrid?: T | ProductGridPropsSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        type?: T;
        style?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  markdown?: T;
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BentoBoxProps_select".
 */
export interface BentoBoxPropsSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        content?: T;
        colSpan?: T;
        rowSpan?: T;
        backgroundColor?: T;
        textAlign?: T;
        id?: T;
      };
  layout?:
    | T
    | {
        columns?: T;
        gap?: T;
        maxWidth?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedProductsProps_select".
 */
export interface FeaturedProductsPropsSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  source?: T;
  promotionalContent?: T;
  collection?: T;
  products?:
    | T
    | {
        productId?: T;
        overrideTitle?: T;
        overrideDescription?: T;
        badge?: T;
        sortOrder?: T;
        id?: T;
      };
  displaySettings?:
    | T
    | {
        layout?: T;
        columns?: T;
        showPrice?: T;
        showBadges?: T;
        maxItems?: T;
      };
  callToAction?:
    | T
    | {
        text?: T;
        link?: T;
        style?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlockProps_select".
 */
export interface HeroBlockPropsSelect<T extends boolean = true> {
  product?:
    | T
    | {
        productId?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HotDealsBlock_select".
 */
export interface HotDealsBlockSelect<T extends boolean = true> {
  products?:
    | T
    | {
        product?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductGridProps_select".
 */
export interface ProductGridPropsSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  source?: T;
  collection?: T;
  products?:
    | T
    | {
        productId?: T;
        sortOrder?: T;
        id?: T;
      };
  displaySettings?:
    | T
    | {
        view?: T;
        columns?: T;
        maxItems?: T;
        showPrices?: T;
        showButtons?: T;
      };
  callToAction?:
    | T
    | {
        text?: T;
        link?: T;
        style?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  points?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotionalContent_select".
 */
export interface PromotionalContentSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  description?: T;
  isActive?: T;
  priority?: T;
  startDate?: T;
  endDate?: T;
  products?:
    | T
    | {
        productId?: T;
        overrideTitle?: T;
        overrideDescription?: T;
        badge?: T;
        sortOrder?: T;
        id?: T;
      };
  heroImage?: T;
  callToAction?:
    | T
    | {
        text?: T;
        link?: T;
        style?: T;
      };
  metadata?:
    | T
    | {
        seoTitle?: T;
        seoDescription?: T;
        displayStyle?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The header of the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  /**
   * The logo to display in the header.
   */
  logo: string | Media;
  /**
   * The navigation items to display in the header.
   */
  navItems: {
    link: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: string | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: string | Post;
          } | null);
      url?: string | null;
      label: string;
    };
    id?: string | null;
  }[];
  /**
   * The featured collections to display in the header.
   */
  collectionItems?:
    | {
        label: string;
        /**
         * Select a collection from the storefront.
         */
        collection: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The footer content of the website. It includes the logo, contact information, quick links, and copyright text.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  /**
   * The logo to display in the footer.
   */
  logo: string | Media;
  /**
   * The contact information to display in the footer.
   */
  contactInformation: {
    /**
     * The email address to display in the footer.
     */
    contactEmail: string;
    /**
     * The phone number to display in the footer.
     */
    contactPhone: string;
    /**
     * The address to display in the footer.
     */
    contactAddress: string;
  };
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * The copyright text to display in the footer.
   */
  copy: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions".
 */
export interface Promotion {
  id: string;
  /**
   * Site-wide promotional banner settings
   */
  sitewideBanner?: {
    /**
     * Show site-wide promotional banner
     */
    isEnabled?: boolean | null;
    /**
     * Banner message text
     */
    message?: string | null;
    /**
     * Background color (hex code)
     */
    backgroundColor?: string | null;
    /**
     * Text color (hex code)
     */
    textColor?: string | null;
    /**
     * Optional link URL
     */
    link?: string | null;
    /**
     * Allow users to dismiss the banner
     */
    dismissible?: boolean | null;
  };
  /**
   * Featured promotional content to display on homepage/landing pages
   */
  featuredContent?:
    | {
        /**
         * Select promotional content to feature
         */
        promotionalContent: string | PromotionalContent;
        /**
         * Display order (higher numbers appear first)
         */
        displayOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Define homepage promotional sections
   */
  homepageSections?:
    | {
        sectionType: 'hero' | 'featuredProducts' | 'bestSellers' | 'campaign' | 'categoryShowcase';
        /**
         * Section title
         */
        title?: string | null;
        /**
         * Section subtitle
         */
        subtitle?: string | null;
        /**
         * Link to promotional content (if applicable)
         */
        content?: (string | null) | PromotionalContent;
        /**
         * Link to collection from storefront API (for category showcase)
         */
        collection?: string | null;
        /**
         * Enable this section
         */
        isEnabled?: boolean | null;
        /**
         * Display order
         */
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Newsletter signup promotional settings
   */
  newsletterPromotion?: {
    /**
     * Show newsletter promotion
     */
    isEnabled?: boolean | null;
    /**
     * Newsletter promotion title
     */
    title?: string | null;
    /**
     * Newsletter promotion description
     */
    description?: string | null;
    /**
     * Discount code to offer for newsletter signup
     */
    discountCode?: string | null;
  };
  /**
   * SEO settings for promotional content
   */
  seoSettings?: {
    /**
     * Default meta title for promotional pages
     */
    metaTitle?: string | null;
    /**
     * Default meta description for promotional pages
     */
    metaDescription?: string | null;
    /**
     * Default Open Graph image for promotional content
     */
    openGraphImage?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  collectionItems?:
    | T
    | {
        label?: T;
        collection?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  contactInformation?:
    | T
    | {
        contactEmail?: T;
        contactPhone?: T;
        contactAddress?: T;
      };
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  copy?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions_select".
 */
export interface PromotionsSelect<T extends boolean = true> {
  sitewideBanner?:
    | T
    | {
        isEnabled?: T;
        message?: T;
        backgroundColor?: T;
        textColor?: T;
        link?: T;
        dismissible?: T;
      };
  featuredContent?:
    | T
    | {
        promotionalContent?: T;
        displayOrder?: T;
        id?: T;
      };
  homepageSections?:
    | T
    | {
        sectionType?: T;
        title?: T;
        subtitle?: T;
        content?: T;
        collection?: T;
        isEnabled?: T;
        sortOrder?: T;
        id?: T;
      };
  newsletterPromotion?:
    | T
    | {
        isEnabled?: T;
        title?: T;
        description?: T;
        discountCode?: T;
      };
  seoSettings?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        openGraphImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}