/* tslint:disable */
/* eslint-disable */
/**
 * PiShop REST API
 * This is the API documentation for PiShop.   It contains all the endpoints for the PiShop API. The API is exposed at [http://shop.pilab.hu/api/v1](http://shop.pilab.hu/api/v1).  The API is based on [OpenAPI](https://swagger.io/specification/), which is a standard for the description of APIs.  # Webshop API Overview  This API provides access to the core functionalities of our webshop, allowing developers to integrate with our platform. Key features include:  * **Product Catalog:** Retrieve detailed information about our products, including descriptions, images, and pricing. * **Cart Management:** Add, remove, and update items in the user\'s cart. * **Order Management:** Create, update, and track customer orders. * **Customer Management:** Manage customer accounts and profiles. * **Discounts and Promotions:** Apply discounts and promotions to products. * **Image Management:** Upload and manage product images. * **Pages and Menus:** Create and manage pages and menus. * **Authentication:** Secure access to protected resources using Bearer authentication (JWT).  This documentation outlines the available endpoints, request/response formats, and authentication procedures. Use this information to build powerful integrations and enhance your customer experience. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: gyula@pilab.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CartItem } from './cartItem';
import {
    CartItemFromJSON,
    CartItemFromJSONTyped,
    CartItemToJSON,
    CartItemToJSONTyped,
} from './cartItem';
import type { CartCost } from './cartCost';
import {
    CartCostFromJSON,
    CartCostFromJSONTyped,
    CartCostToJSON,
    CartCostToJSONTyped,
} from './cartCost';

/**
 * 
 * @export
 * @interface CartResponse
 */
export interface CartResponse {
    /**
     * 
     * @type {string}
     * @memberof CartResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CartResponse
     */
    checkoutUrl?: string;
    /**
     * 
     * @type {CartCost}
     * @memberof CartResponse
     */
    cost?: CartCost;
    /**
     * 
     * @type {number}
     * @memberof CartResponse
     */
    totalQuantity?: number;
    /**
     * 
     * @type {Array<CartItem>}
     * @memberof CartResponse
     */
    lines?: Array<CartItem>;
}

/**
 * Check if a given object implements the CartResponse interface.
 */
export function instanceOfCartResponse(value: object): value is CartResponse {
    return true;
}

export function CartResponseFromJSON(json: any): CartResponse {
    return CartResponseFromJSONTyped(json, false);
}

export function CartResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'checkoutUrl': json['checkoutUrl'] == null ? undefined : json['checkoutUrl'],
        'cost': json['cost'] == null ? undefined : CartCostFromJSON(json['cost']),
        'totalQuantity': json['totalQuantity'] == null ? undefined : json['totalQuantity'],
        'lines': json['lines'] == null ? undefined : ((json['lines'] as Array<any>).map(CartItemFromJSON)),
    };
}

export function CartResponseToJSON(json: any): CartResponse {
    return CartResponseToJSONTyped(json, false);
}

export function CartResponseToJSONTyped(value?: CartResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'checkoutUrl': value['checkoutUrl'],
        'cost': CartCostToJSON(value['cost']),
        'totalQuantity': value['totalQuantity'],
        'lines': value['lines'] == null ? undefined : ((value['lines'] as Array<any>).map(CartItemToJSON)),
    };
}

