/* tslint:disable */
/* eslint-disable */
/**
 * PiShop REST API
 * This is the API documentation for PiShop.   It contains all the endpoints for the PiShop API. The API is exposed at [http://shop.pilab.hu/api/v1](http://shop.pilab.hu/api/v1).  The API is based on [OpenAPI](https://swagger.io/specification/), which is a standard for the description of APIs.  # Webshop API Overview  This API provides access to the core functionalities of our webshop, allowing developers to integrate with our platform. Key features include:  * **Product Catalog:** Retrieve detailed information about our products, including descriptions, images, and pricing. * **Cart Management:** Add, remove, and update items in the user\'s cart. * **Order Management:** Create, update, and track customer orders. * **Customer Management:** Manage customer accounts and profiles. * **Discounts and Promotions:** Apply discounts and promotions to products. * **Image Management:** Upload and manage product images. * **Pages and Menus:** Create and manage pages and menus. * **Authentication:** Secure access to protected resources using Bearer authentication (JWT).  This documentation outlines the available endpoints, request/response formats, and authentication procedures. Use this information to build powerful integrations and enhance your customer experience. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: gyula@pilab.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CartItemLine
 */
export interface CartItemLine {
    /**
     * 
     * @type {string}
     * @memberof CartItemLine
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CartItemLine
     */
    merchandiseId?: string;
    /**
     * 
     * @type {number}
     * @memberof CartItemLine
     */
    quantity?: number;
}

/**
 * Check if a given object implements the CartItemLine interface.
 */
export function instanceOfCartItemLine(value: object): value is CartItemLine {
    return true;
}

export function CartItemLineFromJSON(json: any): CartItemLine {
    return CartItemLineFromJSONTyped(json, false);
}

export function CartItemLineFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartItemLine {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'merchandiseId': json['merchandiseId'] == null ? undefined : json['merchandiseId'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
    };
}

export function CartItemLineToJSON(json: any): CartItemLine {
    return CartItemLineToJSONTyped(json, false);
}

export function CartItemLineToJSONTyped(value?: CartItemLine | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'merchandiseId': value['merchandiseId'],
        'quantity': value['quantity'],
    };
}

