/* tslint:disable */
/* eslint-disable */
/**
 * PiShop REST API
 * This is the API documentation for PiShop.   It contains all the endpoints for the PiShop API. The API is exposed at [http://shop.pilab.hu/api/v1](http://shop.pilab.hu/api/v1).  The API is based on [OpenAPI](https://swagger.io/specification/), which is a standard for the description of APIs.  # Webshop API Overview  This API provides access to the core functionalities of our webshop, allowing developers to integrate with our platform. Key features include:  * **Product Catalog:** Retrieve detailed information about our products, including descriptions, images, and pricing. * **Cart Management:** Add, remove, and update items in the user\'s cart. * **Order Management:** Create, update, and track customer orders. * **Customer Management:** Manage customer accounts and profiles. * **Discounts and Promotions:** Apply discounts and promotions to products. * **Image Management:** Upload and manage product images. * **Pages and Menus:** Create and manage pages and menus. * **Authentication:** Secure access to protected resources using Bearer authentication (JWT).  This documentation outlines the available endpoints, request/response formats, and authentication procedures. Use this information to build powerful integrations and enhance your customer experience. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: gyula@pilab.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Price } from './price';
import {
    PriceFromJSON,
    PriceFromJSONTyped,
    PriceToJSON,
    PriceToJSONTyped,
} from './price';

/**
 * 
 * @export
 * @interface CartItemCost
 */
export interface CartItemCost {
    /**
     * 
     * @type {Price}
     * @memberof CartItemCost
     */
    totalAmount?: Price;
}

/**
 * Check if a given object implements the CartItemCost interface.
 */
export function instanceOfCartItemCost(value: object): value is CartItemCost {
    return true;
}

export function CartItemCostFromJSON(json: any): CartItemCost {
    return CartItemCostFromJSONTyped(json, false);
}

export function CartItemCostFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartItemCost {
    if (json == null) {
        return json;
    }
    return {
        
        'totalAmount': json['totalAmount'] == null ? undefined : PriceFromJSON(json['totalAmount']),
    };
}

export function CartItemCostToJSON(json: any): CartItemCost {
    return CartItemCostToJSONTyped(json, false);
}

export function CartItemCostToJSONTyped(value?: CartItemCost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalAmount': PriceToJSON(value['totalAmount']),
    };
}

