/* tslint:disable */
/* eslint-disable */
/**
 * PiShop REST API
 * This is the API documentation for PiShop.   It contains all the endpoints for the PiShop API. The API is exposed at [http://shop.pilab.hu/api/v1](http://shop.pilab.hu/api/v1).  The API is based on [OpenAPI](https://swagger.io/specification/), which is a standard for the description of APIs.  # Webshop API Overview  This API provides access to the core functionalities of our webshop, allowing developers to integrate with our platform. Key features include:  * **Product Catalog:** Retrieve detailed information about our products, including descriptions, images, and pricing. * **Cart Management:** Add, remove, and update items in the user\'s cart. * **Order Management:** Create, update, and track customer orders. * **Customer Management:** Manage customer accounts and profiles. * **Discounts and Promotions:** Apply discounts and promotions to products. * **Image Management:** Upload and manage product images. * **Pages and Menus:** Create and manage pages and menus. * **Authentication:** Secure access to protected resources using Bearer authentication (JWT).  This documentation outlines the available endpoints, request/response formats, and authentication procedures. Use this information to build powerful integrations and enhance your customer experience. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: gyula@pilab.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateCollection422ResponseFieldsInner } from './createCollection422ResponseFieldsInner';
import {
    CreateCollection422ResponseFieldsInnerFromJSON,
    CreateCollection422ResponseFieldsInnerFromJSONTyped,
    CreateCollection422ResponseFieldsInnerToJSON,
    CreateCollection422ResponseFieldsInnerToJSONTyped,
} from './createCollection422ResponseFieldsInner';

/**
 * 
 * @export
 * @interface CreateCollection422Response
 */
export interface CreateCollection422Response {
    /**
     * 
     * @type {string}
     * @memberof CreateCollection422Response
     */
    error: string;
    /**
     * 
     * @type {Array<CreateCollection422ResponseFieldsInner>}
     * @memberof CreateCollection422Response
     */
    fields: Array<CreateCollection422ResponseFieldsInner>;
}

/**
 * Check if a given object implements the CreateCollection422Response interface.
 */
export function instanceOfCreateCollection422Response(value: object): value is CreateCollection422Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('fields' in value) || value['fields'] === undefined) return false;
    return true;
}

export function CreateCollection422ResponseFromJSON(json: any): CreateCollection422Response {
    return CreateCollection422ResponseFromJSONTyped(json, false);
}

export function CreateCollection422ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCollection422Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
        'fields': ((json['fields'] as Array<any>).map(CreateCollection422ResponseFieldsInnerFromJSON)),
    };
}

export function CreateCollection422ResponseToJSON(json: any): CreateCollection422Response {
    return CreateCollection422ResponseToJSONTyped(json, false);
}

export function CreateCollection422ResponseToJSONTyped(value?: CreateCollection422Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'fields': ((value['fields'] as Array<any>).map(CreateCollection422ResponseFieldsInnerToJSON)),
    };
}

