/* tslint:disable */
/* eslint-disable */
/**
 * PiShop REST API
 * This is the API documentation for PiShop.   It contains all the endpoints for the PiShop API. The API is exposed at [http://shop.pilab.hu/api/v1](http://shop.pilab.hu/api/v1).  The API is based on [OpenAPI](https://swagger.io/specification/), which is a standard for the description of APIs.  # Webshop API Overview  This API provides access to the core functionalities of our webshop, allowing developers to integrate with our platform. Key features include:  * **Product Catalog:** Retrieve detailed information about our products, including descriptions, images, and pricing. * **Cart Management:** Add, remove, and update items in the user\'s cart. * **Order Management:** Create, update, and track customer orders. * **Customer Management:** Manage customer accounts and profiles. * **Discounts and Promotions:** Apply discounts and promotions to products. * **Image Management:** Upload and manage product images. * **Pages and Menus:** Create and manage pages and menus. * **Authentication:** Secure access to protected resources using Bearer authentication (JWT).  This documentation outlines the available endpoints, request/response formats, and authentication procedures. Use this information to build powerful integrations and enhance your customer experience. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: gyula@pilab.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCollection422ResponseFieldsInner
 */
export interface CreateCollection422ResponseFieldsInner {
    /**
     * 
     * @type {string}
     * @memberof CreateCollection422ResponseFieldsInner
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCollection422ResponseFieldsInner
     */
    path?: string;
}

/**
 * Check if a given object implements the CreateCollection422ResponseFieldsInner interface.
 */
export function instanceOfCreateCollection422ResponseFieldsInner(value: object): value is CreateCollection422ResponseFieldsInner {
    return true;
}

export function CreateCollection422ResponseFieldsInnerFromJSON(json: any): CreateCollection422ResponseFieldsInner {
    return CreateCollection422ResponseFieldsInnerFromJSONTyped(json, false);
}

export function CreateCollection422ResponseFieldsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCollection422ResponseFieldsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function CreateCollection422ResponseFieldsInnerToJSON(json: any): CreateCollection422ResponseFieldsInner {
    return CreateCollection422ResponseFieldsInnerToJSONTyped(json, false);
}

export function CreateCollection422ResponseFieldsInnerToJSONTyped(value?: CreateCollection422ResponseFieldsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'path': value['path'],
    };
}

