/* tslint:disable */
/* eslint-disable */
/**
 * PiShop REST API
 * This is the API documentation for PiShop.   It contains all the endpoints for the PiShop API. The API is exposed at [http://shop.pilab.hu/api/v1](http://shop.pilab.hu/api/v1).  The API is based on [OpenAPI](https://swagger.io/specification/), which is a standard for the description of APIs.  # Webshop API Overview  This API provides access to the core functionalities of our webshop, allowing developers to integrate with our platform. Key features include:  * **Product Catalog:** Retrieve detailed information about our products, including descriptions, images, and pricing. * **Cart Management:** Add, remove, and update items in the user\'s cart. * **Order Management:** Create, update, and track customer orders. * **Customer Management:** Manage customer accounts and profiles. * **Discounts and Promotions:** Apply discounts and promotions to products. * **Image Management:** Upload and manage product images. * **Pages and Menus:** Create and manage pages and menus. * **Authentication:** Secure access to protected resources using Bearer authentication (JWT).  This documentation outlines the available endpoints, request/response formats, and authentication procedures. Use this information to build powerful integrations and enhance your customer experience. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: gyula@pilab.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SelectedOption } from './selectedOption';
import {
    SelectedOptionFromJSON,
    SelectedOptionFromJSONTyped,
    SelectedOptionToJSON,
    SelectedOptionToJSONTyped,
} from './selectedOption';
import type { MerchandiseProduct } from './merchandiseProduct';
import {
    MerchandiseProductFromJSON,
    MerchandiseProductFromJSONTyped,
    MerchandiseProductToJSON,
    MerchandiseProductToJSONTyped,
} from './merchandiseProduct';

/**
 * 
 * @export
 * @interface Merchandise
 */
export interface Merchandise {
    /**
     * 
     * @type {string}
     * @memberof Merchandise
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Merchandise
     */
    title?: string;
    /**
     * 
     * @type {Array<SelectedOption>}
     * @memberof Merchandise
     */
    selectedOptions?: Array<SelectedOption>;
    /**
     * 
     * @type {MerchandiseProduct}
     * @memberof Merchandise
     */
    product?: MerchandiseProduct;
}

/**
 * Check if a given object implements the Merchandise interface.
 */
export function instanceOfMerchandise(value: object): value is Merchandise {
    return true;
}

export function MerchandiseFromJSON(json: any): Merchandise {
    return MerchandiseFromJSONTyped(json, false);
}

export function MerchandiseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Merchandise {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'selectedOptions': json['selectedOptions'] == null ? undefined : ((json['selectedOptions'] as Array<any>).map(SelectedOptionFromJSON)),
        'product': json['product'] == null ? undefined : MerchandiseProductFromJSON(json['product']),
    };
}

export function MerchandiseToJSON(json: any): Merchandise {
    return MerchandiseToJSONTyped(json, false);
}

export function MerchandiseToJSONTyped(value?: Merchandise | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'selectedOptions': value['selectedOptions'] == null ? undefined : ((value['selectedOptions'] as Array<any>).map(SelectedOptionToJSON)),
        'product': MerchandiseProductToJSON(value['product']),
    };
}

