/* tslint:disable */
/* eslint-disable */
/**
 * PiShop REST API
 * This is the API documentation for PiShop.   It contains all the endpoints for the PiShop API. The API is exposed at [http://shop.pilab.hu/api/v1](http://shop.pilab.hu/api/v1).  The API is based on [OpenAPI](https://swagger.io/specification/), which is a standard for the description of APIs.  # Webshop API Overview  This API provides access to the core functionalities of our webshop, allowing developers to integrate with our platform. Key features include:  * **Product Catalog:** Retrieve detailed information about our products, including descriptions, images, and pricing. * **Cart Management:** Add, remove, and update items in the user\'s cart. * **Order Management:** Create, update, and track customer orders. * **Customer Management:** Manage customer accounts and profiles. * **Discounts and Promotions:** Apply discounts and promotions to products. * **Image Management:** Upload and manage product images. * **Pages and Menus:** Create and manage pages and menus. * **Authentication:** Secure access to protected resources using Bearer authentication (JWT).  This documentation outlines the available endpoints, request/response formats, and authentication procedures. Use this information to build powerful integrations and enhance your customer experience. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: gyula@pilab.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductImage } from './productImage';
import {
    ProductImageFromJSON,
    ProductImageFromJSONTyped,
    ProductImageToJSON,
    ProductImageToJSONTyped,
} from './productImage';

/**
 * 
 * @export
 * @interface MerchandiseProduct
 */
export interface MerchandiseProduct {
    /**
     * 
     * @type {string}
     * @memberof MerchandiseProduct
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof MerchandiseProduct
     */
    handle?: string;
    /**
     * 
     * @type {string}
     * @memberof MerchandiseProduct
     */
    title?: string;
    /**
     * 
     * @type {ProductImage}
     * @memberof MerchandiseProduct
     */
    featuredImage?: ProductImage;
}

/**
 * Check if a given object implements the MerchandiseProduct interface.
 */
export function instanceOfMerchandiseProduct(value: object): value is MerchandiseProduct {
    return true;
}

export function MerchandiseProductFromJSON(json: any): MerchandiseProduct {
    return MerchandiseProductFromJSONTyped(json, false);
}

export function MerchandiseProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): MerchandiseProduct {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'handle': json['handle'] == null ? undefined : json['handle'],
        'title': json['title'] == null ? undefined : json['title'],
        'featuredImage': json['featuredImage'] == null ? undefined : ProductImageFromJSON(json['featuredImage']),
    };
}

export function MerchandiseProductToJSON(json: any): MerchandiseProduct {
    return MerchandiseProductToJSONTyped(json, false);
}

export function MerchandiseProductToJSONTyped(value?: MerchandiseProduct | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'handle': value['handle'],
        'title': value['title'],
        'featuredImage': ProductImageToJSON(value['featuredImage']),
    };
}

