/* tslint:disable */
/* eslint-disable */
/**
 * PiShop REST API
 * This is the API documentation for PiShop.   It contains all the endpoints for the PiShop API. The API is exposed at [http://shop.pilab.hu/api/v1](http://shop.pilab.hu/api/v1).  The API is based on [OpenAPI](https://swagger.io/specification/), which is a standard for the description of APIs.  # Webshop API Overview  This API provides access to the core functionalities of our webshop, allowing developers to integrate with our platform. Key features include:  * **Product Catalog:** Retrieve detailed information about our products, including descriptions, images, and pricing. * **Cart Management:** Add, remove, and update items in the user\'s cart. * **Order Management:** Create, update, and track customer orders. * **Customer Management:** Manage customer accounts and profiles. * **Discounts and Promotions:** Apply discounts and promotions to products. * **Image Management:** Upload and manage product images. * **Pages and Menus:** Create and manage pages and menus. * **Authentication:** Secure access to protected resources using Bearer authentication (JWT).  This documentation outlines the available endpoints, request/response formats, and authentication procedures. Use this information to build powerful integrations and enhance your customer experience. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: gyula@pilab.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductImage
 */
export interface ProductImage {
    /**
     * URL of the product image
     * @type {string}
     * @memberof ProductImage
     */
    url: string;
    /**
     * Alternative text for the image
     * @type {string}
     * @memberof ProductImage
     */
    altText: string;
    /**
     * Width of the image in pixels. Used for responsive images.
     * @type {number}
     * @memberof ProductImage
     */
    width?: number;
    /**
     * Height of the image in pixels. Used for responsive images.
     * @type {number}
     * @memberof ProductImage
     */
    height?: number;
}

/**
 * Check if a given object implements the ProductImage interface.
 */
export function instanceOfProductImage(value: object): value is ProductImage {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('altText' in value) || value['altText'] === undefined) return false;
    return true;
}

export function ProductImageFromJSON(json: any): ProductImage {
    return ProductImageFromJSONTyped(json, false);
}

export function ProductImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductImage {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'altText': json['altText'],
        'width': json['width'] == null ? undefined : json['width'],
        'height': json['height'] == null ? undefined : json['height'],
    };
}

export function ProductImageToJSON(json: any): ProductImage {
    return ProductImageToJSONTyped(json, false);
}

export function ProductImageToJSONTyped(value?: ProductImage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'altText': value['altText'],
        'width': value['width'],
        'height': value['height'],
    };
}

