/* tslint:disable */
/* eslint-disable */
/**
 * PiShop REST API
 * This is the API documentation for PiShop.   It contains all the endpoints for the PiShop API. The API is exposed at [http://shop.pilab.hu/api/v1](http://shop.pilab.hu/api/v1).  The API is based on [OpenAPI](https://swagger.io/specification/), which is a standard for the description of APIs.  # Webshop API Overview  This API provides access to the core functionalities of our webshop, allowing developers to integrate with our platform. Key features include:  * **Product Catalog:** Retrieve detailed information about our products, including descriptions, images, and pricing. * **Cart Management:** Add, remove, and update items in the user\'s cart. * **Order Management:** Create, update, and track customer orders. * **Customer Management:** Manage customer accounts and profiles. * **Discounts and Promotions:** Apply discounts and promotions to products. * **Image Management:** Upload and manage product images. * **Pages and Menus:** Create and manage pages and menus. * **Authentication:** Secure access to protected resources using Bearer authentication (JWT).  This documentation outlines the available endpoints, request/response formats, and authentication procedures. Use this information to build powerful integrations and enhance your customer experience. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: gyula@pilab.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductTypeInput
 */
export interface ProductTypeInput {
    /**
     * URL-friendly handle
     * @type {string}
     * @memberof ProductTypeInput
     */
    handle: string;
    /**
     * Display name of the product type
     * @type {string}
     * @memberof ProductTypeInput
     */
    name: string;
    /**
     * Description of the product type
     * @type {string}
     * @memberof ProductTypeInput
     */
    description?: string;
    /**
     * IDs of metadata fields associated with this product type
     * @type {Array<string>}
     * @memberof ProductTypeInput
     */
    metadataFieldIds: Array<string>;
    /**
     * Template suffix for custom templates
     * @type {string}
     * @memberof ProductTypeInput
     */
    templateSuffix?: string;
}

/**
 * Check if a given object implements the ProductTypeInput interface.
 */
export function instanceOfProductTypeInput(value: object): value is ProductTypeInput {
    if (!('handle' in value) || value['handle'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('metadataFieldIds' in value) || value['metadataFieldIds'] === undefined) return false;
    return true;
}

export function ProductTypeInputFromJSON(json: any): ProductTypeInput {
    return ProductTypeInputFromJSONTyped(json, false);
}

export function ProductTypeInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductTypeInput {
    if (json == null) {
        return json;
    }
    return {
        
        'handle': json['handle'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'metadataFieldIds': json['metadataFieldIds'],
        'templateSuffix': json['templateSuffix'] == null ? undefined : json['templateSuffix'],
    };
}

export function ProductTypeInputToJSON(json: any): ProductTypeInput {
    return ProductTypeInputToJSONTyped(json, false);
}

export function ProductTypeInputToJSONTyped(value?: ProductTypeInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'handle': value['handle'],
        'name': value['name'],
        'description': value['description'],
        'metadataFieldIds': value['metadataFieldIds'],
        'templateSuffix': value['templateSuffix'],
    };
}

